apiVersion: v1
kind: Service
metadata:
  name: {{ include "maildev.fullname" . }}
  labels:
    {{- include "maildev.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.web }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.mail }}
      targetPort: mail
      protocol: TCP
      name: mail
  selector:
    {{- include "maildev.selectorLabels" . | nindent 4 }}
